#!/usr/bin/env python3
#-*- coding = utf-8 -*-

import sys
import importlib

def main():
	mod = importlib.import_module('lib.main')
	if len(sys.argv) < 2:
		print("\nError: no argument was provided!\n")
		mod.main(['-h'])
	else:
		mod.main(sys.argv[1:])

if __name__ == '__main__':
	main()
